# Generated by Django 2.2.4 on 2019-08-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='upvote_price',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
