# Generated by Django 2.2.4 on 2019-09-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_suggestioncomment'),
        ('accounts', '0008_remove_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suggestion_upvotes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='suggestions.Suggestion'),
        ),
    ]
