# Generated by Django 2.2.4 on 2019-09-06 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0005_reviewcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewComment',
            new_name='Comment',
        ),
    ]
