# Generated by Django 2.2.4 on 2019-09-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190906_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='written_by',
        ),
    ]
