# Generated by Django 2.2.4 on 2019-08-20 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
